'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Reviews',
      [
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 4,
          restId: 1,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 2,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 2,
          restId: 1,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 1,
          restId: 2,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 2,
          restId: 3,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 4,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 4,
          restId: 5,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 5,
          restId: 6,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 4,
          restId: 7,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 8,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 2,
          restId: 9,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 1,
          restId: 10,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 2,
          restId: 11,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 12,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 4,
          restId: 13,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 5,
          restId: 14,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 4,
          restId: 1,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 2,
          restId: 14,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 1,
          restId: 13,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 2,
          restId: 12,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 11,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 4,
          restId: 10,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 5,
          restId: 9,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 4,
          restId: 8,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 7,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 2,
          restId: 6,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 1,
          restId: 5,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 2,
          restId: 4,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 3,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 4,
          restId: 2,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 5,
          restId: 1,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 2,
        },
                {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 2,
          restId: 14,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 1,
          restId: 13,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 2,
          restId: 12,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 11,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 4,
          restId: 10,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 5,
          restId: 9,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 4,
          restId: 8,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 7,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 2,
          restId: 6,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 1,
          restId: 5,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 2,
          restId: 4,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 3,
          restId: 3,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 4,
          restId: 2,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 5,
          restId: 1,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 5,
          restId: 14,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 4,
          restId: 12,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 3,
          restId: 10,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 2,
          restId: 8,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 1,
          restId: 6,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 2,
          restId: 4,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 3,
          restId: 2,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 4,
          restId: 1,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 5,
          restId: 3,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 4,
          restId: 5,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 3,
          userId: 3,
          restId: 7,
        },
        {
          text: 'Bad!',
          images: [''],
          score: 2,
          userId: 2,
          restId: 9,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 1,
          restId: 11,
        },
        {
          text: 'Good!',
          images: [''],
          score: 8,
          userId: 2,
          restId: 13,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Reviews', null, {});
  },
};
